spring:
  profiles:
    active: home-local
  application:
    name: big-data

  datasource:
    hikari:
      maximum-pool-size: 5000  # 设置最大连接数，确保足够支持您的并发需求
      minimum-idle: 10  # 设置最小空闲连接数，确保连接的快速获取
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
server:
  port: 80
